import pandas as pd

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/genotype.smk"
include: "rules/parallelism.smk"
include: "rules/variant_catalog.smk"

localrules: all, test


SAMPLES = pd.read_table(config["samples"]).set_index("Sample", drop=False).join(METADATA)
VARIANTS = config["variants"] 

rule all:
    input:
        expand("results/{variant}/{sample}/{sample}_realigned.bam", variant=VARIANTS, sample=SAMPLES.index),
        expand("results/{variant}/{sample}/{sample}_realigned.bam.bai", variant=VARIANTS, sample=SAMPLES.index)

rule test:
    input:
        "results/{}/{}/{}_realigned.bam".format(VARIANTS[0], SAMPLES.index[0], SAMPLES.index[0]),
        "results/{}/{}/{}_realigned.bam.bai".format(VARIANTS[0], SAMPLES.index[0], SAMPLES.index[0])
